services:
  app:
    build: .
    container_name: panel_app
    ports:
      - "5006:5006"
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: aws_local
    ports:
      - "127.0.0.1:4566:4566"

    environment:
      SERVICES: s3

      # Configuraciones de AWS para el awslocal CLI
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1

      # Habilita el modo de depuración para ver más logs
      DEBUG: 1

    volumes:
      - ./localstack:/etc/localstack/init/ready.d  # scripts de inicialización
